import { setRequestLocale } from "next-intl/server";
import { buildPageMetadata } from "@/lib/seo/metadata";
import { contactInfo } from "@/lib/data/academy";
import { words } from "@/lib/club";
import { PageIntro, SectionHeading } from "@/components/club/ClubUI";
import { ContactForm } from "@/components/forms/ContactForm";
import { Link } from "@/lib/i18n/navigation";
type Props={params:Promise<{locale:string}>;searchParams:Promise<{subject?:string}>};
export async function generateMetadata({params}:Props){const{locale}=await params;return buildPageMetadata({locale,path:"/contact",title:words(locale,"Contact et accès","Contact and visits"),description:words(locale,"Contacter Ninety One Foot Academy à Douala : candidature, partenariat et informations.","Contact Ninety One Foot Academy in Douala: admissions, partnerships and information.")});}
export default async function Contact({params,searchParams}:Props){const{locale}=await params;setRequestLocale(locale);const{subject}=await searchParams;const initialSubject=subject==="partnership"?words(locale,"Devenir partenaire de l’académie","Become an academy partner"):"";return <><PageIntro title={words(locale,"Parlons de votre projet.","Let’s talk.")} eyebrow={words(locale,"Contact & accès","Contact & visits")} description={words(locale,"Une question, une candidature ou l’envie de nous accompagner ? Échangeons.","A question, an application or a partnership idea? Get in touch.")}/><div className="club-container club-section"><div className="club-team-layout"><section id="formulaire"><SectionHeading title={words(locale,"Écrire à l’académie","Write to the academy")}/><ContactForm initialSubject={initialSubject} key={initialSubject}/><p className="mt-5 text-xs leading-6 text-text-muted">{words(locale,"Vos coordonnées servent à répondre à votre demande.","Your contact details are used to respond to your request.")} <Link className="underline" href="/confidentialite">{words(locale,"Confidentialité","Privacy")}</Link></p></section><aside><section id="venir" className="portal-practical"><p className="club-kicker">{words(locale,"Venir nous rencontrer","Visit us")}</p><h2 className="my-4 text-2xl font-bold">Douala, Cameroun</h2><p>{words(locale,"Contactez l’académie avant votre déplacement pour confirmer le lieu et l’horaire du rendez-vous. Aucune adresse de stade précise n’est publiée pour le moment.","Contact the academy before travelling to confirm the meeting location and time. A specific stadium address has not yet been published.")}</p><a className="club-text-link break-all" href={"mailto:"+contactInfo.email}>{contactInfo.email}</a></section><section className="pt-8"><h2 className="mb-4 text-lg font-bold">{words(locale,"Suivre le club","Follow the club")}</h2><div className="flex flex-wrap gap-6"><a href={contactInfo.social.instagram} className="club-text-link" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href={contactInfo.social.facebook} className="club-text-link" target="_blank" rel="noopener noreferrer">Facebook ↗</a></div><Link className="club-text-link" href="/rejoindre">{words(locale,"Déposer une candidature","Apply to the academy")} →</Link></section></aside></div></div></>;}
