import Image from "next/image";
import { getTranslations } from "next-intl/server";
import { Link } from "@/lib/i18n/navigation";
import { historyContent, dimensions, academySummary, whyReasons, visionContent, values } from "@/lib/data/academy";
import { programSteps, playerBenefits, sportDimensions, weeklyProgram, educationSections, performanceTools } from "@/lib/data/program";
import { staffMembers } from "@/lib/data/staff";
import { words } from "@/lib/club";
import { PageIntro, SectionHeading, ActionLink } from "./ClubUI";
import type { Locale, LocalizedString } from "@/types";
export type AcademyKind="academy"|"vision"|"program"|"training"|"education"|"performanceLab"|"coaching";
function List({items,locale}:{items:LocalizedString[];locale:Locale}){return <ul className="grid gap-3 sm:grid-cols-2">{items.map((item,i)=><li className="flex items-start gap-3 border-b border-black/10 py-3 text-sm" key={item.fr}><span className="font-bold text-royal">{String(i+1).padStart(2,"0")}</span>{item[locale]}</li>)}</ul>;}
export async function AcademyContent({kind,locale}:{kind:AcademyKind;locale:Locale}){
 const titles={academy:words(locale,"Le club, notre académie","Our club, our academy"),vision:words(locale,"Une vision. Des valeurs.","A vision. Shared values."),program:words(locale,"Le programme 2026–2029","The 2026–2029 programme"),training:words(locale,"La formation sportive","Football development"),education:words(locale,"Grandir au-delà du terrain","Growing beyond the pitch"),performanceLab:"Performance Lab",coaching:words(locale,"L’encadrement","Coaching staff")};
 const translation=kind!=="coaching"?await getTranslations({locale,namespace:kind}):null;
 return <><PageIntro title={titles[kind]} eyebrow="NINETY ONE FOOT ACADEMY" image={kind==="education"?"/promise-02.png":kind==="performanceLab"?"/promise-03.png":"/hero-3.jpeg"}/><div className="club-container club-section">
 {kind==="academy"&&<><nav className="club-tabs" aria-label={words(locale,"Sections du club","Club sections")}><a href="#histoire">{words(locale,"Histoire","History")}</a><a href="#projet">{words(locale,"Projet","Project")}</a><a href="#reperes">{words(locale,"Repères","At a glance")}</a><a href="#engagements">{words(locale,"Engagements","Commitments")}</a></nav><section id="histoire" className="club-editorial-row"><div className="editorial-image"><Image src="/hero-4.jpeg" alt="" fill sizes="(min-width:768px) 40vw, 100vw"/></div><div><p className="club-kicker">DOUALA · 2026–2029</p><h2>{translation!("historyTitle")}</h2><p>{historyContent[locale]}</p></div></section><section id="projet" className="club-section"><SectionHeading title={translation!("approachTitle")}/><div className="grid gap-7 sm:grid-cols-2">{dimensions.map((d,i)=><div className="club-staff-role" key={d.id}><p className="club-kicker">0{i+1}</p><h3>{d.title[locale]}</h3><p>{d.description[locale]}</p></div>)}</div></section><section id="reperes"><SectionHeading title={translation!("summaryTitle")}/><dl className="grid gap-4 md:grid-cols-2">{academySummary.map(s=><div className="flex flex-wrap justify-between gap-3 border-b border-black/10 py-5" key={s.label.fr}><dt className="text-sm text-text-muted">{s.label[locale]}</dt><dd className="font-semibold">{s.value[locale]}</dd></div>)}</dl></section><section id="engagements" className="club-section"><SectionHeading title={translation!("whyTitle")}/><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{whyReasons.map(r=><div key={r.id}><h3 className="mb-3 font-bold">{r.title[locale]}</h3><p className="text-sm leading-7 text-text-muted">{r.description[locale]}</p></div>)}</div></section><ActionLink href="/contact#venir">{words(locale,"Rencontrer l’académie","Meet the academy")}</ActionLink></>}
 {kind==="vision"&&<><div className="club-reading">{(["vision","mission","engagement"] as const).map((key,i)=><section key={key}><p className="club-kicker">0{i+1}</p><h2>{translation!(key+"Title")}</h2><p>{visionContent[key][locale]}</p></section>)}</div><section className="club-section"><SectionHeading title={translation!("valuesTitle")}/><div className="grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{values.map(v=><div className="club-staff-role" key={v.id}><h3>{v.title[locale]}</h3><p>{v.description[locale]}</p></div>)}</div></section><blockquote className="border-l-4 border-gold py-4 pl-6 text-2xl font-semibold">{translation!("quote")}</blockquote></>}
 {kind==="program"&&<><SectionHeading title={translation!("timelineTitle")}/><ol>{programSteps.map((s,i)=><li key={s.id} id={s.id} className="club-editorial-row"><div><p className="club-kicker">{words(locale,"Étape","Stage")} 0{i+1}</p><h2>{s.title[locale]}</h2><p>{s.description[locale]}</p></div><div className="border-l-2 border-gold pl-7"><p>{s.details[locale]}</p></div></li>)}</ol><section className="club-section"><SectionHeading title={translation!("benefitsTitle")}/><List items={playerBenefits} locale={locale}/></section><ActionLink href="/rejoindre">{words(locale,"Candidater à l’académie","Apply to the academy")}</ActionLink></>}
 {kind==="training"&&<><SectionHeading title={translation!("dimensionsTitle")}/><div className="grid gap-8 sm:grid-cols-2">{sportDimensions.map((d,i)=><div className="club-staff-role" key={d.title.fr}><p className="club-kicker">0{i+1}</p><h3>{d.title[locale]}</h3><p>{d.description[locale]}</p></div>)}</div><section className="club-editorial-row"><div className="editorial-image"><Image src="/promise-01.png" alt="" fill sizes="(min-width:768px) 40vw, 100vw"/></div><div><h2>{translation!("weeklyTitle")}</h2><List items={weeklyProgram} locale={locale}/></div></section><ActionLink href="/equipes">{words(locale,"Découvrir les catégories","Explore the age groups")}</ActionLink></>}
 {kind==="education"&&<>{(["academic","personal","future"] as const).map((key,i)=><section className="club-editorial-row" key={key}><div><p className="club-kicker">0{i+1}</p><h2>{translation!(key+"Title")}</h2></div><List items={educationSections[key]} locale={locale}/></section>)}<blockquote className="border-l-4 border-gold py-4 pl-6 text-2xl font-semibold">{translation!("quote")}</blockquote></>}
 {kind==="performanceLab"&&<><SectionHeading title={translation!("toolsTitle")}/><div className="grid gap-8 sm:grid-cols-2">{performanceTools.map((t,i)=><div className="club-staff-role" key={t.title.fr}><p className="club-kicker">0{i+1}</p><h3>{t.title[locale]}</h3><p>{t.description[locale]}</p></div>)}</div><section className="club-editorial-row"><div className="editorial-image"><Image src="/promise-03.png" alt="" fill sizes="(min-width:768px) 40vw, 100vw"/></div><div><h2>{translation!("methodTitle")}</h2><p>{words(locale,"La donnée transforme l’entraînement en progression mesurable. Chaque séance, chaque match et chaque test alimentent un suivi personnalisé qui guide le joueur et le staff.","Data turns training into measurable progress. Each session, match and test informs individual monitoring for players and staff.")}</p><p className="mt-5">{words(locale,"Le suivi individuel est réservé aux joueurs, aux familles et au staff dans l’espace privé.","Individual monitoring is reserved for players, families and staff in the member area.")}</p><Link className="club-text-link" href="/login">{words(locale,"Accéder à l’espace privé","Go to the member area")} →</Link></div></section></>}
 {kind==="coaching"&&<><SectionHeading title={words(locale,"Une équipe autour du joueur","A team around each player")}/><div className="grid gap-x-12 sm:grid-cols-2">{staffMembers.map(s=><section className="club-staff-role" key={s.id}><h3>{s.role[locale]}</h3><p>{s.bio[locale]}</p><small>{s.name==="À confirmer"?words(locale,"Nom à confirmer","Name to be confirmed"):s.name}</small></section>)}</div><div className="mt-10"><ActionLink href="/equipes">{words(locale,"L’encadrement par catégorie","Coaching by age group")}</ActionLink></div></>}
 </div></>;
}
