import Image from "next/image";
import { setRequestLocale } from "next-intl/server";
import { partners, partnerBenefits } from "@/lib/data/partners";
import { buildPageMetadata } from "@/lib/seo/metadata";
import { words } from "@/lib/club";
import { PageIntro, SectionHeading, ActionLink } from "@/components/club/ClubUI";
import type { Locale } from "@/types";
export async function generateMetadata({params}:{params:Promise<{locale:string}>}){const{locale}=await params;return buildPageMetadata({locale,path:"/partenaires",title:words(locale,"Nos partenaires","Our partners"),description:words(locale,"Les partenaires qui accompagnent Ninety One Foot Academy.","The partners supporting Ninety One Foot Academy.")});}
export default async function Partners({params}:{params:Promise<{locale:string}>}){const{locale}=await params;setRequestLocale(locale);const loc=locale as Locale;return <><PageIntro title={words(loc,"Grandir ensemble.","Growing together.")} eyebrow={words(loc,"Partenaires & entreprises","Partners & businesses")} description={words(loc,"Des partenaires engagés dans la formation de la nouvelle génération.","Partners committed to developing the next generation.")} image="/hero-3.jpeg"/><div className="club-container club-section"><SectionHeading title={words(loc,"Ils font partie du projet","Part of the project")}/>{partners.map(p=><article id={p.id} key={p.id} className="club-partner-detail"><div className="partner-logo">{p.logo&&<Image src={p.logo} alt={p.name} fill sizes="250px" className="object-contain"/>}</div><div><p className="club-kicker">{p.role[loc]}</p><h2>{p.name}</h2><p>{p.description[loc]}</p>{p.website&&<a className="club-text-link" href={p.website} target="_blank" rel="noopener noreferrer">{words(loc,"Visiter le site du partenaire","Visit partner website")} ↗</a>}</div></article>)}<section id="devenir-partenaire" className="pt-14"><SectionHeading title={words(loc,"Accompagner notre vision","Support our vision")}/><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{partnerBenefits.map(b=><div key={b.title.fr}><h3 className="mb-3 text-lg font-bold">{b.title[loc]}</h3><p className="text-sm leading-7 text-text-muted">{b.description[loc]}</p></div>)}</div><div className="mt-8 flex flex-wrap gap-4"><ActionLink href="/contact?subject=partnership#formulaire">{words(loc,"Parlons de votre engagement","Let’s discuss your involvement")}</ActionLink><ActionLink href="/parrains" secondary>{words(loc,"Nos parrains & ambassadeurs","Our patrons & ambassadors")}</ActionLink></div></section></div></>;}
