import { notFound } from "next/navigation";
import Image from "next/image";
import { setRequestLocale } from "next-intl/server";
import { Link } from "@/lib/i18n/navigation";
import { buildPageMetadata } from "@/lib/seo/metadata";
import { teamCategories } from "@/lib/data/staff";
import { matches, publicPlayers, words } from "@/lib/club";
import { PageIntro, EmptyState, MatchCard, SectionHeading, ActionLink } from "@/components/club/ClubUI";
import type { Locale } from "@/types";
type Props={params:Promise<{locale:string;slug:string}>};
export const dynamicParams = false;
export function generateStaticParams(){return teamCategories.map(t=>({slug:t.id}));}
export async function generateMetadata({params}:Props){const{locale,slug}=await params;const t=teamCategories.find(t=>t.id===slug);if(!t)return{};return buildPageMetadata({locale,path:"/equipes/"+slug,title:t.label[locale as Locale],description:t.description[locale as Locale]});}
export default async function Team({params}:Props){const{locale,slug}=await params;setRequestLocale(locale);const loc=locale as Locale;const team=teamCategories.find(t=>t.id===slug);if(!team)notFound();const players=publicPlayers.filter(p=>p.teamId===team.id);const fixtures=matches.filter(m=>m.teamId===team.id);return <><PageIntro title={team.label[loc]} eyebrow={words(loc,"Nos équipes","Our teams")} description={team.description[loc]} image={team.image}/><nav className="club-subnav" aria-label={words(loc,"Sur cette page","On this page")}><div className="club-container"><a href="#effectif">{words(loc,"Effectif","Squad")}</a><a href="#staff">{words(loc,"Encadrement","Staff")}</a><a href="#rencontres">{words(loc,"Rencontres","Fixtures")}</a><Link href="/equipes">← {words(loc,"Toutes les équipes","All teams")}</Link></div></nav><div className="club-container club-section"><div className="club-team-layout"><section id="effectif"><SectionHeading title={words(loc,"L’effectif","The squad")}/>{players.length?<div className="grid gap-5 sm:grid-cols-2">{players.map(p=><Link className="club-team-card" key={p.slug} href={"/joueurs/"+p.slug}>{p.image&&<div className="news-image"><Image src={p.image} alt="" fill sizes="40vw"/></div>}<div className="news-copy"><h3>{p.name}</h3><p>{p.position[loc]}</p></div></Link>)}</div>:<EmptyState title={words(loc,"Effectif en cours de présentation","Squad presentation coming soon")}>{words(loc,"Les profils des joueurs seront disponibles après confirmation des informations publiques.","Player profiles will be available once their public information is confirmed.")}</EmptyState>}</section><section id="staff"><SectionHeading title={words(loc,"L’encadrement","Coaching staff")}/>{team.coaches.map(c=><div className="club-staff-role" key={c.id}><h3>{c.role[loc]}</h3><p>{c.bio[loc]}</p><small>{c.name==="À confirmer"?words(loc,"Nom à confirmer","Name to be confirmed"):c.name}</small></div>)}</section></div><section id="rencontres" className="pt-12"><SectionHeading title={words(loc,"Les rencontres","Fixtures")} href={"/saison?team="+team.id} linkLabel={words(loc,"Voir la saison","View season")}/>{fixtures.length?<div className="club-card-grid">{fixtures.slice(0,3).map(m=><MatchCard match={m} locale={loc} key={m.id}/>)}</div>:<EmptyState title={words(loc,"Calendrier à venir","Fixtures to be announced")}>{words(loc,"Les prochaines rencontres seront publiées dès confirmation.","Upcoming fixtures will be published once confirmed.")}</EmptyState>}</section><div className="mt-10"><ActionLink href="/rejoindre">{words(loc,"Découvrir les candidatures","Explore admissions")}</ActionLink></div></div></>;}
