import { setRequestLocale } from "next-intl/server";
import { Link } from "@/lib/i18n/navigation";
import { buildPageMetadata } from "@/lib/seo/metadata";
import { matches, standings, words } from "@/lib/club";
import { teamCategories } from "@/lib/data/staff";
import { PageIntro, EmptyState, MatchCard, Standings } from "@/components/club/ClubUI";
import type { Locale } from "@/types";
type Props={params:Promise<{locale:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
export async function generateMetadata({params}:Props){const{locale}=await params;return buildPageMetadata({locale,path:"/saison",title:words(locale,"Saison : calendrier et résultats","Season: fixtures and results"),description:words(locale,"Retrouvez les rencontres et classements des équipes de Ninety One Foot Academy.","Fixtures, results and standings for Ninety One Foot Academy teams.")});}
export default async function Season({params,searchParams}:Props){
 const{locale}=await params;setRequestLocale(locale);const loc=locale as Locale;const query=await searchParams;const val=(key:string)=>typeof query[key]==="string"?query[key] as string:"";
 const view=["results","standings"].includes(val("view"))?val("view"):"fixtures";const team=val("team"),season=val("season"),competition=val("competition"),venue=val("venue");
 const filtered=matches.filter(m=>(!team||m.teamId===team)&&(!season||m.season===season)&&(!competition||m.competition===competition)&&(!venue||(venue==="home"?m.isHome:!m.isHome))&&(view==="results"?m.status==="finished":m.status!=="finished")).sort((a,b)=>(view==="results"?-1:1)*(a.date??"9999").localeCompare(b.date??"9999"));
 const snapshots=standings.filter(s=>(!team||s.teamId===team)&&(!season||s.season===season)&&(!competition||s.competition===competition));
 const tabHref=(v:string)=>"/saison?"+new URLSearchParams({view:v,team,season,competition,venue});
 return <><PageIntro title={words(loc,"La saison du club","The club season")} eyebrow="NINETY ONE FOOT ACADEMY" description={words(loc,"Nos équipes, leurs rencontres et leurs résultats.","Our teams, fixtures and results.")}/><div className="club-container club-section">
  <nav className="club-tabs" aria-label={words(loc,"Rubriques saison","Season sections")}>{[["fixtures",words(loc,"Calendrier","Fixtures")],["results",words(loc,"Résultats","Results")],["standings",words(loc,"Classement","Standings")]].map(([v,label])=><Link key={v} href={tabHref(v)} aria-current={view===v?"page":undefined}>{label}</Link>)}</nav>
  <form className="club-filters" method="get"><input type="hidden" name="view" value={view}/><label>{words(loc,"Équipe","Team")}<select name="team" defaultValue={team}><option value="">{words(loc,"Toutes les équipes","All teams")}</option>{teamCategories.map(t=><option key={t.id} value={t.id}>{t.shortLabel[loc]}</option>)}</select></label><label>{words(loc,"Saison","Season")}<select name="season" defaultValue={season}><option value="">{words(loc,"Toutes les saisons","All seasons")}</option>{[...new Set([...matches,...standings].map(m=>m.season))].map(s=><option key={s}>{s}</option>)}</select></label><label>{words(loc,"Compétition","Competition")}<select name="competition" defaultValue={competition}><option value="">{words(loc,"Toutes les compétitions","All competitions")}</option>{[...new Set([...matches,...standings].map(m=>m.competition))].map(s=><option key={s}>{s}</option>)}</select></label>{view!=="standings"&&<label>{words(loc,"Lieu","Venue")}<select name="venue" defaultValue={venue}><option value="">{words(loc,"Tous les matchs","All fixtures")}</option><option value="home">{words(loc,"Domicile","Home")}</option><option value="away">{words(loc,"Extérieur","Away")}</option></select></label>}<button className="club-button">{words(loc,"Filtrer","Filter")}</button></form>
  {view==="standings"?(snapshots.length?snapshots.map(s=><Standings key={s.teamId+s.competition+s.season} snapshot={s} locale={loc}/>):<EmptyState title={words(loc,"Classement non publié","Standings not published")} href="/equipes" label={words(loc,"Découvrir les équipes","Explore our teams")}>{words(loc,"Aucun classement officiel n’est disponible pour cette sélection. Les données seront affichées après confirmation.","No official standings are available for this selection. Data will be shown once confirmed.")}</EmptyState>):filtered.length?<div className="club-card-grid">{filtered.map(m=><MatchCard key={m.id} match={m} locale={loc}/>)}</div>:<EmptyState title={view==="results"?words(loc,"Aucun résultat publié","No results published"):words(loc,"Calendrier à venir","Fixtures to be announced")} href="/actualites?category=matches" label={words(loc,"Lire les actualités sportives","Read football news")}>{words(loc,"Aucune rencontre officielle n’est publiée pour cette sélection. Retrouvez en attendant la vie des équipes dans les actualités.","No confirmed fixtures have been published for this selection. Explore team stories in the meantime.")}</EmptyState>}
 </div></>;
}
